### ISSUE TITLE
Dataset open-source available

### ISSUE THREAD

**Issue by nirat1606** [allenai/gpv2-web10k#1]
Thank you for this interesting work and making the code available. 

The code for downloading query images is provided using Bing Image Search. I was wondering if the dataset can be made available via google drive etc, everyone would not need to use query scripts to download separately? Is that feasible?

Thanks,
Nirat

**Comment by amitakamath** [comment]
Hi Nirat, thank you for your interest in our work! Unfortunately, because the Bing Image Search is a paid API, we can't open-source the images/URLs themselves. However, the API is quite affordable (we downloaded about 1M images for ~$150); you can get it [here](https://www.microsoft.com/en-us/bing/apis/bing-image-search-api).
